### ISSUE TITLE
looking for string in wrong lang folder

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-tinymce_tiny_mce_wiris#1] opened 2017-03-08 13:46 UTC
We use the en_us lang pack for Moodle.  However, wiris doesn't have an en_us langpack, but it also doesn't fall back to en.  In both tinymce and atto this error occurs.

GET https://moodle-dev.rose-hulman.edu/lib/editor/tinymce/plugins/tiny_mce_wiris/tinymce/lang/en_us/strings.js 
wrs_waitForCore @ editor.js:188

**Comment by manuelwiris** [comment] 2017-08-08 14:19
Hi @Syxton 

The issue is fixed in our last release: #11

**Closed by manuelwiris** 2017-08-08 14:19 UTC
