### ISSUE TITLE
Conflict HTML sources editor

### ISSUE THREAD

**Issue by andurif** [wiris/moodle-tinymce_tiny_mce_wiris#35] opened 2018-10-10 15:59 UTC
Hello, we use your plugin since a few month and we found a suspect behaiviour after an update.
We started by update the plugin from version 7.0.0.1386 to version 7.6.1.1393. No problem to insert equation or formula but when we want edit HTML source it's impossible to update content (through the HTML source editor pop-up). Same thing even if we have only "classic" HTML and no equation.

I suppose there was a bug because when I clicked on the "Update" button of the editor I saw the error below in my Chrome Console.
```js
editor_plugin.src.js:322 Uncaught ReferenceError: Parse is not defined
    at Editor.eval (editor_plugin.src.js:322)
    at Dispatcher.dispatch (tiny_mce_src.js:561)
    at Editor.setContent (tiny_mce_src.js:14487)
    at saveContent (VM348 source_editor.js:5)
    at HTMLFormElement.onsubmit (VM353 source_editor.htm:1)
```

We have the same behaiviour and error after a new plugin update to the last version (7.7.0.1394) and this problem diseappear if we disable the plugin. I also tried to change some code but without success.

Regards.

**Comment by Ravoit** [comment] 2018-10-25 11:16
Same. Breaks html editor and fullscreen.

**Comment by andurif** [comment] 2018-10-29 15:25
Hello, it seems resolved for me after another update to the last version (7.7.2.1396).

**Comment by Ravoit** [comment] 2018-11-01 08:16
Updated to 7.7.2.1396, still same problems.

**Comment by manuelwiris** [comment] 2018-11-01 11:29
Hi @Ravoit, thanks for your feedback. 

Could you provide us more details about your issue (Moodle version, browser..) ? We can't reproduce the issue into our end.

**Comment by dcanet-at-wiris** [comment] 2021-06-18 11:33
Closing the issue since there is no feedback

**Closed by dcanet-at-wiris** 2021-06-18 11:33 UTC
Labels: state:accepted
